# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Morgane Steins
email: morgane.steins@enpc.fr morgane.steins@cea.fr
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://morganesteins.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  MorganeSteins
og_image: /assets/img/profile-pic.jpg

# Build settings
# theme: minimal
remote_theme: eliottvincent/bay
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  #   - .sass-cache/
  #   - .jekyll-cache/
  #   - gemfiles/
  #   - Gemfile
  #   - Gemfile.lock
  #   - node_modules/
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/
  - _posts/

header:
  pages:
    - name: Home
      slug: /
    - name: Français
      link: /français

footer:
  contact:
    - name: email
      value: morgane.steins@enpc.fr
      link: mailto:morgane.steins@enpc.fr
    - name: email
      value: morgane.steins@cea.fr
      link: "mailto:morgane.steins@cea.fr"
    - name: tel
      value: "01.69.08.87.92"
  follow:
    - name: GitHub
      link: http://github.com/MorganeSteins

    - name: ResearchGate
      value: RG
      link: https://www.researchgate.net/profile/Morgane_Steins

    - name: linkedIn
      value: LinkedIn
      link: https://www.linkedin.com/in/morgane-steins/
    
    - name: orcid
      value: OrcID
      link: https://orcid.org/0000-0002-3938-5265
